package com.models_generator.main.enums;

public enum RelationshipType {
    ASSOCIATION,
    AGGREGATION,
    COMPOSITION,
    GENERALIZATION,
    DEPENDENCY,
    REALIZATION,
    IMPLEMENTATION,
    INHERITANCE,
    REALIZATION_INHERITANCE,
    IMPLEMENTATION_INHERITANCE,
    DEPENDENCY_INHERITANCE,
    AGGREGATION_INHERITANCE,
    COMPOSITION_INHERITANCE,
    ASSOCIATION_INHERITANCE,
}
